package main

import (
	"context"
	"fmt"
	"log"

	_ "github.com/gogf/gf/contrib/drivers/pgsql/v2" // Or whichever postgres driver gf uses
	"github.com/gogf/gf/v2/database/gdb"
)

func main() {
	gdb.SetConfig(gdb.Config{
		"default": gdb.ConfigGroup{
			gdb.ConfigNode{
				Type: "pgsql",
				Link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/cex",
			},
		},
	})

	db, err := gdb.New()
	if err != nil {
		log.Fatal(err)
	}

	query := `ALTER TABLE t_app_user_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;`

	_, err = db.Exec(context.Background(), query)
	if err != nil {
		fmt.Printf("Error altering id to IDENTITY: %v\n", err)
		// Maybe it's a serial that is already there or different syntax
		query2 := `CREATE SEQUENCE IF NOT EXISTS t_app_user_address_id_seq;
		ALTER TABLE t_app_user_address ALTER COLUMN id SET DEFAULT nextval('t_app_user_address_id_seq');
		ALTER SEQUENCE t_app_user_address_id_seq OWNED BY t_app_user_address.id;`
		_, err2 := db.Exec(context.Background(), query2)
		if err2 != nil {
			fmt.Printf("Error creating sequence: %v\n", err2)
		} else {
			fmt.Println("Successfully fixed via SEQUENCE")
		}
	} else {
		fmt.Println("Successfully fixed via IDENTITY")
	}

	// Wait, we also need to fix other tables if they aren't auto-increment?
	// The user only complained about this one for now. Let's just fix this one.
}
