// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// activityRechargeDao is the data access object for the table t_activity_recharge.
// You can define custom methods on it to extend its functionality as needed.
type activityRechargeDao struct {
	*internal.ActivityRechargeDao
}

var (
	// ActivityRecharge is a globally accessible object for table t_activity_recharge operations.
	ActivityRecharge = activityRechargeDao{internal.NewActivityRechargeDao()}
)

// Add your custom methods and functionality below.
