// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// activityDao is the data access object for the table t_activity.
// You can define custom methods on it to extend its functionality as needed.
type activityDao struct {
	*internal.ActivityDao
}

var (
	// Activity is a globally accessible object for table t_activity operations.
	Activity = activityDao{internal.NewActivityDao()}
)

// Add your custom methods and functionality below.
