// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// agentActivityInfoDao is the data access object for the table t_agent_activity_info.
// You can define custom methods on it to extend its functionality as needed.
type agentActivityInfoDao struct {
	*internal.AgentActivityInfoDao
}

var (
	// AgentActivityInfo is a globally accessible object for table t_agent_activity_info operations.
	AgentActivityInfo = agentActivityInfoDao{internal.NewAgentActivityInfoDao()}
)

// Add your custom methods and functionality below.
