// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appAddressInfoDao is the data access object for the table t_app_address_info.
// You can define custom methods on it to extend its functionality as needed.
type appAddressInfoDao struct {
	*internal.AppAddressInfoDao
}

var (
	// AppAddressInfo is a globally accessible object for table t_app_address_info operations.
	AppAddressInfo = appAddressInfoDao{internal.NewAppAddressInfoDao()}
)

// Add your custom methods and functionality below.
