// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appMailDao is the data access object for the table t_app_mail.
// You can define custom methods on it to extend its functionality as needed.
type appMailDao struct {
	*internal.AppMailDao
}

var (
	// AppMail is a globally accessible object for table t_app_mail operations.
	AppMail = appMailDao{internal.NewAppMailDao()}
)

// Add your custom methods and functionality below.
