// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appWalletRecordDao is the data access object for the table t_app_wallet_record.
// You can define custom methods on it to extend its functionality as needed.
type appWalletRecordDao struct {
	*internal.AppWalletRecordDao
}

var (
	// AppWalletRecord is a globally accessible object for table t_app_wallet_record operations.
	AppWalletRecord = appWalletRecordDao{internal.NewAppWalletRecordDao()}
)

// Add your custom methods and functionality below.
