// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appAssetDao is the data access object for the table t_app_asset.
// You can define custom methods on it to extend its functionality as needed.
type appAssetDao struct {
	*internal.AppAssetDao
}

var (
	// AppAsset is a globally accessible object for table t_app_asset operations.
	AppAsset = appAssetDao{internal.NewAppAssetDao()}
)

// Add your custom methods and functionality below.
