// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appUserDetailDao is the data access object for the table t_app_user_detail.
// You can define custom methods on it to extend its functionality as needed.
type appUserDetailDao struct {
	*internal.AppUserDetailDao
}

var (
	// AppUserDetail is a globally accessible object for table t_app_user_detail operations.
	AppUserDetail = appUserDetailDao{internal.NewAppUserDetailDao()}
)

// Add your custom methods and functionality below.
