// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appUserAddressDao is the data access object for the table t_app_user_address.
// You can define custom methods on it to extend its functionality as needed.
type appUserAddressDao struct {
	*internal.AppUserAddressDao
}

var (
	// AppUserAddress is a globally accessible object for table t_app_user_address operations.
	AppUserAddress = appUserAddressDao{internal.NewAppUserAddressDao()}
)

// Add your custom methods and functionality below.
