// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appUserDao is the data access object for the table t_app_user.
// You can define custom methods on it to extend its functionality as needed.
type appUserDao struct {
	*internal.AppUserDao
}

var (
	// AppUser is a globally accessible object for table t_app_user operations.
	AppUser = appUserDao{internal.NewAppUserDao()}
)

// Add your custom methods and functionality below.
