// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appRechargeDao is the data access object for the table t_app_recharge.
// You can define custom methods on it to extend its functionality as needed.
type appRechargeDao struct {
	*internal.AppRechargeDao
}

var (
	// AppRecharge is a globally accessible object for table t_app_recharge operations.
	AppRecharge = appRechargeDao{internal.NewAppRechargeDao()}
)

// Add your custom methods and functionality below.
