// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appSubTransferDao is the data access object for the table t_app_sub_transfer.
// You can define custom methods on it to extend its functionality as needed.
type appSubTransferDao struct {
	*internal.AppSubTransferDao
}

var (
	// AppSubTransfer is a globally accessible object for table t_app_sub_transfer operations.
	AppSubTransfer = appSubTransferDao{internal.NewAppSubTransferDao()}
)

// Add your custom methods and functionality below.
