// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// appuserLoginLogDao is the data access object for the table t_appuser_login_log.
// You can define custom methods on it to extend its functionality as needed.
type appuserLoginLogDao struct {
	*internal.AppuserLoginLogDao
}

var (
	// AppuserLoginLog is a globally accessible object for table t_appuser_login_log operations.
	AppuserLoginLog = appuserLoginLogDao{internal.NewAppuserLoginLogDao()}
)

// Add your custom methods and functionality below.
