// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// botKlineModelInfoDao is the data access object for the table t_bot_kline_model_info.
// You can define custom methods on it to extend its functionality as needed.
type botKlineModelInfoDao struct {
	*internal.BotKlineModelInfoDao
}

var (
	// BotKlineModelInfo is a globally accessible object for table t_bot_kline_model_info operations.
	BotKlineModelInfo = botKlineModelInfoDao{internal.NewBotKlineModelInfoDao()}
)

// Add your custom methods and functionality below.
