// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// botKlineModelDao is the data access object for the table t_bot_kline_model.
// You can define custom methods on it to extend its functionality as needed.
type botKlineModelDao struct {
	*internal.BotKlineModelDao
}

var (
	// BotKlineModel is a globally accessible object for table t_bot_kline_model operations.
	BotKlineModel = botKlineModelDao{internal.NewBotKlineModelDao()}
)

// Add your custom methods and functionality below.
