// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// collectionOrderDao is the data access object for the table t_collection_order.
// You can define custom methods on it to extend its functionality as needed.
type collectionOrderDao struct {
	*internal.CollectionOrderDao
}

var (
	// CollectionOrder is a globally accessible object for table t_collection_order operations.
	CollectionOrder = collectionOrderDao{internal.NewCollectionOrderDao()}
)

// Add your custom methods and functionality below.
