// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// contractLossDao is the data access object for the table t_contract_loss.
// You can define custom methods on it to extend its functionality as needed.
type contractLossDao struct {
	*internal.ContractLossDao
}

var (
	// ContractLoss is a globally accessible object for table t_contract_loss operations.
	ContractLoss = contractLossDao{internal.NewContractLossDao()}
)

// Add your custom methods and functionality below.
