// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// contractOrderDao is the data access object for the table t_contract_order.
// You can define custom methods on it to extend its functionality as needed.
type contractOrderDao struct {
	*internal.ContractOrderDao
}

var (
	// ContractOrder is a globally accessible object for table t_contract_order operations.
	ContractOrder = contractOrderDao{internal.NewContractOrderDao()}
)

// Add your custom methods and functionality below.
