// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// contractPositionDao is the data access object for the table t_contract_position.
// You can define custom methods on it to extend its functionality as needed.
type contractPositionDao struct {
	*internal.ContractPositionDao
}

var (
	// ContractPosition is a globally accessible object for table t_contract_position operations.
	ContractPosition = contractPositionDao{internal.NewContractPositionDao()}
)

// Add your custom methods and functionality below.
