// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// contractCoinDao is the data access object for the table t_contract_coin.
// You can define custom methods on it to extend its functionality as needed.
type contractCoinDao struct {
	*internal.ContractCoinDao
}

var (
	// ContractCoin is a globally accessible object for table t_contract_coin operations.
	ContractCoin = contractCoinDao{internal.NewContractCoinDao()}
)

// Add your custom methods and functionality below.
