// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// currencySymbolDao is the data access object for the table t_currency_symbol.
// You can define custom methods on it to extend its functionality as needed.
type currencySymbolDao struct {
	*internal.CurrencySymbolDao
}

var (
	// CurrencySymbol is a globally accessible object for table t_currency_symbol operations.
	CurrencySymbol = currencySymbolDao{internal.NewCurrencySymbolDao()}
)

// Add your custom methods and functionality below.
