// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// currencyOrderDao is the data access object for the table t_currency_order.
// You can define custom methods on it to extend its functionality as needed.
type currencyOrderDao struct {
	*internal.CurrencyOrderDao
}

var (
	// CurrencyOrder is a globally accessible object for table t_currency_order operations.
	CurrencyOrder = currencyOrderDao{internal.NewCurrencyOrderDao()}
)

// Add your custom methods and functionality below.
