// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// defiRateDao is the data access object for the table t_defi_rate.
// You can define custom methods on it to extend its functionality as needed.
type defiRateDao struct {
	*internal.DefiRateDao
}

var (
	// DefiRate is a globally accessible object for table t_defi_rate operations.
	DefiRate = defiRateDao{internal.NewDefiRateDao()}
)

// Add your custom methods and functionality below.
