// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// defiActivityDao is the data access object for the table t_defi_activity.
// You can define custom methods on it to extend its functionality as needed.
type defiActivityDao struct {
	*internal.DefiActivityDao
}

var (
	// DefiActivity is a globally accessible object for table t_defi_activity operations.
	DefiActivity = defiActivityDao{internal.NewDefiActivityDao()}
)

// Add your custom methods and functionality below.
