// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// defiOrderDao is the data access object for the table t_defi_order.
// You can define custom methods on it to extend its functionality as needed.
type defiOrderDao struct {
	*internal.DefiOrderDao
}

var (
	// DefiOrder is a globally accessible object for table t_defi_order operations.
	DefiOrder = defiOrderDao{internal.NewDefiOrderDao()}
)

// Add your custom methods and functionality below.
