// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// exchangeCoinRecordDao is the data access object for the table t_exchange_coin_record.
// You can define custom methods on it to extend its functionality as needed.
type exchangeCoinRecordDao struct {
	*internal.ExchangeCoinRecordDao
}

var (
	// ExchangeCoinRecord is a globally accessible object for table t_exchange_coin_record operations.
	ExchangeCoinRecord = exchangeCoinRecordDao{internal.NewExchangeCoinRecordDao()}
)

// Add your custom methods and functionality below.
