// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// genTableColumnDao is the data access object for the table gen_table_column.
// You can define custom methods on it to extend its functionality as needed.
type genTableColumnDao struct {
	*internal.GenTableColumnDao
}

var (
	// GenTableColumn is a globally accessible object for table gen_table_column operations.
	GenTableColumn = genTableColumnDao{internal.NewGenTableColumnDao()}
)

// Add your custom methods and functionality below.
