// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// genTableDao is the data access object for the table gen_table.
// You can define custom methods on it to extend its functionality as needed.
type genTableDao struct {
	*internal.GenTableDao
}

var (
	// GenTable is a globally accessible object for table gen_table operations.
	GenTable = genTableDao{internal.NewGenTableDao()}
)

// Add your custom methods and functionality below.
