// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// helpCenterDao is the data access object for the table t_help_center.
// You can define custom methods on it to extend its functionality as needed.
type helpCenterDao struct {
	*internal.HelpCenterDao
}

var (
	// HelpCenter is a globally accessible object for table t_help_center operations.
	HelpCenter = helpCenterDao{internal.NewHelpCenterDao()}
)

// Add your custom methods and functionality below.
