// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// helpCenterInfoDao is the data access object for the table t_help_center_info.
// You can define custom methods on it to extend its functionality as needed.
type helpCenterInfoDao struct {
	*internal.HelpCenterInfoDao
}

var (
	// HelpCenterInfo is a globally accessible object for table t_help_center_info operations.
	HelpCenterInfo = helpCenterInfoDao{internal.NewHelpCenterInfoDao()}
)

// Add your custom methods and functionality below.
