// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// homeSetterDao is the data access object for the table t_home_setter.
// You can define custom methods on it to extend its functionality as needed.
type homeSetterDao struct {
	*internal.HomeSetterDao
}

var (
	// HomeSetter is a globally accessible object for table t_home_setter operations.
	HomeSetter = homeSetterDao{internal.NewHomeSetterDao()}
)

// Add your custom methods and functionality below.
