// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// klineSymbolDao is the data access object for the table t_kline_symbol.
// You can define custom methods on it to extend its functionality as needed.
type klineSymbolDao struct {
	*internal.KlineSymbolDao
}

var (
	// KlineSymbol is a globally accessible object for table t_kline_symbol operations.
	KlineSymbol = klineSymbolDao{internal.NewKlineSymbolDao()}
)

// Add your custom methods and functionality below.
