// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// loadOrderDao is the data access object for the table t_load_order.
// You can define custom methods on it to extend its functionality as needed.
type loadOrderDao struct {
	*internal.LoadOrderDao
}

var (
	// LoadOrder is a globally accessible object for table t_load_order operations.
	LoadOrder = loadOrderDao{internal.NewLoadOrderDao()}
)

// Add your custom methods and functionality below.
