// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// loadProductDao is the data access object for the table t_load_product.
// You can define custom methods on it to extend its functionality as needed.
type loadProductDao struct {
	*internal.LoadProductDao
}

var (
	// LoadProduct is a globally accessible object for table t_load_product operations.
	LoadProduct = loadProductDao{internal.NewLoadProductDao()}
)

// Add your custom methods and functionality below.
