// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// marketsDao is the data access object for the table t_markets.
// You can define custom methods on it to extend its functionality as needed.
type marketsDao struct {
	*internal.MarketsDao
}

var (
	// Markets is a globally accessible object for table t_markets operations.
	Markets = marketsDao{internal.NewMarketsDao()}
)

// Add your custom methods and functionality below.
