// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mineOrderDao is the data access object for the table t_mine_order.
// You can define custom methods on it to extend its functionality as needed.
type mineOrderDao struct {
	*internal.MineOrderDao
}

var (
	// MineOrder is a globally accessible object for table t_mine_order operations.
	MineOrder = mineOrderDao{internal.NewMineOrderDao()}
)

// Add your custom methods and functionality below.
