// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mineOrderDayDao is the data access object for the table t_mine_order_day.
// You can define custom methods on it to extend its functionality as needed.
type mineOrderDayDao struct {
	*internal.MineOrderDayDao
}

var (
	// MineOrderDay is a globally accessible object for table t_mine_order_day operations.
	MineOrderDay = mineOrderDayDao{internal.NewMineOrderDayDao()}
)

// Add your custom methods and functionality below.
