// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mineFinancialDao is the data access object for the table t_mine_financial.
// You can define custom methods on it to extend its functionality as needed.
type mineFinancialDao struct {
	*internal.MineFinancialDao
}

var (
	// MineFinancial is a globally accessible object for table t_mine_financial operations.
	MineFinancial = mineFinancialDao{internal.NewMineFinancialDao()}
)

// Add your custom methods and functionality below.
