// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mineUserDao is the data access object for the table t_mine_user.
// You can define custom methods on it to extend its functionality as needed.
type mineUserDao struct {
	*internal.MineUserDao
}

var (
	// MineUser is a globally accessible object for table t_mine_user operations.
	MineUser = mineUserDao{internal.NewMineUserDao()}
)

// Add your custom methods and functionality below.
