// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mingProductDao is the data access object for the table t_ming_product.
// You can define custom methods on it to extend its functionality as needed.
type mingProductDao struct {
	*internal.MingProductDao
}

var (
	// MingProduct is a globally accessible object for table t_ming_product operations.
	MingProduct = mingProductDao{internal.NewMingProductDao()}
)

// Add your custom methods and functionality below.
