// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mingOrderDao is the data access object for the table t_ming_order.
// You can define custom methods on it to extend its functionality as needed.
type mingOrderDao struct {
	*internal.MingOrderDao
}

var (
	// MingOrder is a globally accessible object for table t_ming_order operations.
	MingOrder = mingOrderDao{internal.NewMingOrderDao()}
)

// Add your custom methods and functionality below.
