// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// mingProductUserDao is the data access object for the table t_ming_product_user.
// You can define custom methods on it to extend its functionality as needed.
type mingProductUserDao struct {
	*internal.MingProductUserDao
}

var (
	// MingProductUser is a globally accessible object for table t_ming_product_user operations.
	MingProductUser = mingProductUserDao{internal.NewMingProductUserDao()}
)

// Add your custom methods and functionality below.
