// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// noticeDao is the data access object for the table t_notice.
// You can define custom methods on it to extend its functionality as needed.
type noticeDao struct {
	*internal.NoticeDao
}

var (
	// Notice is a globally accessible object for table t_notice operations.
	Notice = noticeDao{internal.NewNoticeDao()}
)

// Add your custom methods and functionality below.
