// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// optionRulesDao is the data access object for the table t_option_rules.
// You can define custom methods on it to extend its functionality as needed.
type optionRulesDao struct {
	*internal.OptionRulesDao
}

var (
	// OptionRules is a globally accessible object for table t_option_rules operations.
	OptionRules = optionRulesDao{internal.NewOptionRulesDao()}
)

// Add your custom methods and functionality below.
