// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// ownCoinOrderDao is the data access object for the table t_own_coin_order.
// You can define custom methods on it to extend its functionality as needed.
type ownCoinOrderDao struct {
	*internal.OwnCoinOrderDao
}

var (
	// OwnCoinOrder is a globally accessible object for table t_own_coin_order operations.
	OwnCoinOrder = ownCoinOrderDao{internal.NewOwnCoinOrderDao()}
)

// Add your custom methods and functionality below.
