// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// ownCoinSubscribeOrderDao is the data access object for the table t_own_coin_subscribe_order.
// You can define custom methods on it to extend its functionality as needed.
type ownCoinSubscribeOrderDao struct {
	*internal.OwnCoinSubscribeOrderDao
}

var (
	// OwnCoinSubscribeOrder is a globally accessible object for table t_own_coin_subscribe_order operations.
	OwnCoinSubscribeOrder = ownCoinSubscribeOrderDao{internal.NewOwnCoinSubscribeOrderDao()}
)

// Add your custom methods and functionality below.
