// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzSimpropTriggersDao is the data access object for the table qrtz_simprop_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzSimpropTriggersDao struct {
	*internal.QrtzSimpropTriggersDao
}

var (
	// QrtzSimpropTriggers is a globally accessible object for table qrtz_simprop_triggers operations.
	QrtzSimpropTriggers = qrtzSimpropTriggersDao{internal.NewQrtzSimpropTriggersDao()}
)

// Add your custom methods and functionality below.
