// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzLocksDao is the data access object for the table qrtz_locks.
// You can define custom methods on it to extend its functionality as needed.
type qrtzLocksDao struct {
	*internal.QrtzLocksDao
}

var (
	// QrtzLocks is a globally accessible object for table qrtz_locks operations.
	QrtzLocks = qrtzLocksDao{internal.NewQrtzLocksDao()}
)

// Add your custom methods and functionality below.
