// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzCronTriggersDao is the data access object for the table qrtz_cron_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzCronTriggersDao struct {
	*internal.QrtzCronTriggersDao
}

var (
	// QrtzCronTriggers is a globally accessible object for table qrtz_cron_triggers operations.
	QrtzCronTriggers = qrtzCronTriggersDao{internal.NewQrtzCronTriggersDao()}
)

// Add your custom methods and functionality below.
