// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzCalendarsDao is the data access object for the table qrtz_calendars.
// You can define custom methods on it to extend its functionality as needed.
type qrtzCalendarsDao struct {
	*internal.QrtzCalendarsDao
}

var (
	// QrtzCalendars is a globally accessible object for table qrtz_calendars operations.
	QrtzCalendars = qrtzCalendarsDao{internal.NewQrtzCalendarsDao()}
)

// Add your custom methods and functionality below.
