// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzFiredTriggersDao is the data access object for the table qrtz_fired_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzFiredTriggersDao struct {
	*internal.QrtzFiredTriggersDao
}

var (
	// QrtzFiredTriggers is a globally accessible object for table qrtz_fired_triggers operations.
	QrtzFiredTriggers = qrtzFiredTriggersDao{internal.NewQrtzFiredTriggersDao()}
)

// Add your custom methods and functionality below.
