// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzJobDetailsDao is the data access object for the table qrtz_job_details.
// You can define custom methods on it to extend its functionality as needed.
type qrtzJobDetailsDao struct {
	*internal.QrtzJobDetailsDao
}

var (
	// QrtzJobDetails is a globally accessible object for table qrtz_job_details operations.
	QrtzJobDetails = qrtzJobDetailsDao{internal.NewQrtzJobDetailsDao()}
)

// Add your custom methods and functionality below.
