// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzTriggersDao is the data access object for the table qrtz_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzTriggersDao struct {
	*internal.QrtzTriggersDao
}

var (
	// QrtzTriggers is a globally accessible object for table qrtz_triggers operations.
	QrtzTriggers = qrtzTriggersDao{internal.NewQrtzTriggersDao()}
)

// Add your custom methods and functionality below.
