// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzSimpleTriggersDao is the data access object for the table qrtz_simple_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzSimpleTriggersDao struct {
	*internal.QrtzSimpleTriggersDao
}

var (
	// QrtzSimpleTriggers is a globally accessible object for table qrtz_simple_triggers operations.
	QrtzSimpleTriggers = qrtzSimpleTriggersDao{internal.NewQrtzSimpleTriggersDao()}
)

// Add your custom methods and functionality below.
