// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzSchedulerStateDao is the data access object for the table qrtz_scheduler_state.
// You can define custom methods on it to extend its functionality as needed.
type qrtzSchedulerStateDao struct {
	*internal.QrtzSchedulerStateDao
}

var (
	// QrtzSchedulerState is a globally accessible object for table qrtz_scheduler_state operations.
	QrtzSchedulerState = qrtzSchedulerStateDao{internal.NewQrtzSchedulerStateDao()}
)

// Add your custom methods and functionality below.
