// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzPausedTriggerGrpsDao is the data access object for the table qrtz_paused_trigger_grps.
// You can define custom methods on it to extend its functionality as needed.
type qrtzPausedTriggerGrpsDao struct {
	*internal.QrtzPausedTriggerGrpsDao
}

var (
	// QrtzPausedTriggerGrps is a globally accessible object for table qrtz_paused_trigger_grps operations.
	QrtzPausedTriggerGrps = qrtzPausedTriggerGrpsDao{internal.NewQrtzPausedTriggerGrpsDao()}
)

// Add your custom methods and functionality below.
