// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// qrtzBlobTriggersDao is the data access object for the table qrtz_blob_triggers.
// You can define custom methods on it to extend its functionality as needed.
type qrtzBlobTriggersDao struct {
	*internal.QrtzBlobTriggersDao
}

var (
	// QrtzBlobTriggers is a globally accessible object for table qrtz_blob_triggers operations.
	QrtzBlobTriggers = qrtzBlobTriggersDao{internal.NewQrtzBlobTriggersDao()}
)

// Add your custom methods and functionality below.
