// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// secondContractOrderDao is the data access object for the table t_second_contract_order.
// You can define custom methods on it to extend its functionality as needed.
type secondContractOrderDao struct {
	*internal.SecondContractOrderDao
}

var (
	// SecondContractOrder is a globally accessible object for table t_second_contract_order operations.
	SecondContractOrder = secondContractOrderDao{internal.NewSecondContractOrderDao()}
)

// Add your custom methods and functionality below.
