// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// secondCoinConfigDao is the data access object for the table t_second_coin_config.
// You can define custom methods on it to extend its functionality as needed.
type secondCoinConfigDao struct {
	*internal.SecondCoinConfigDao
}

var (
	// SecondCoinConfig is a globally accessible object for table t_second_coin_config operations.
	SecondCoinConfig = secondCoinConfigDao{internal.NewSecondCoinConfigDao()}
)

// Add your custom methods and functionality below.
