// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// secondPeriodConfigDao is the data access object for the table t_second_period_config.
// You can define custom methods on it to extend its functionality as needed.
type secondPeriodConfigDao struct {
	*internal.SecondPeriodConfigDao
}

var (
	// SecondPeriodConfig is a globally accessible object for table t_second_period_config operations.
	SecondPeriodConfig = secondPeriodConfigDao{internal.NewSecondPeriodConfigDao()}
)

// Add your custom methods and functionality below.
