// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// spontaneousCoinDao is the data access object for the table t_spontaneous_coin.
// You can define custom methods on it to extend its functionality as needed.
type spontaneousCoinDao struct {
	*internal.SpontaneousCoinDao
}

var (
	// SpontaneousCoin is a globally accessible object for table t_spontaneous_coin operations.
	SpontaneousCoin = spontaneousCoinDao{internal.NewSpontaneousCoinDao()}
)

// Add your custom methods and functionality below.
