// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// symbolsDao is the data access object for the table t_symbols.
// You can define custom methods on it to extend its functionality as needed.
type symbolsDao struct {
	*internal.SymbolsDao
}

var (
	// Symbols is a globally accessible object for table t_symbols operations.
	Symbols = symbolsDao{internal.NewSymbolsDao()}
)

// Add your custom methods and functionality below.
