// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// symbolManageDao is the data access object for the table t_symbol_manage.
// You can define custom methods on it to extend its functionality as needed.
type symbolManageDao struct {
	*internal.SymbolManageDao
}

var (
	// SymbolManage is a globally accessible object for table t_symbol_manage operations.
	SymbolManage = symbolManageDao{internal.NewSymbolManageDao()}
)

// Add your custom methods and functionality below.
