// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// sysRoleDeptDao is the data access object for the table sys_role_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleDeptDao struct {
	*internal.SysRoleDeptDao
}

var (
	// SysRoleDept is a globally accessible object for table sys_role_dept operations.
	SysRoleDept = sysRoleDeptDao{internal.NewSysRoleDeptDao()}
)

// Add your custom methods and functionality below.
