// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// userCoinDao is the data access object for the table t_user_coin.
// You can define custom methods on it to extend its functionality as needed.
type userCoinDao struct {
	*internal.UserCoinDao
}

var (
	// UserCoin is a globally accessible object for table t_user_coin operations.
	UserCoin = userCoinDao{internal.NewUserCoinDao()}
)

// Add your custom methods and functionality below.
