// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// userSymbolAddressDao is the data access object for the table t_user_symbol_address.
// You can define custom methods on it to extend its functionality as needed.
type userSymbolAddressDao struct {
	*internal.UserSymbolAddressDao
}

var (
	// UserSymbolAddress is a globally accessible object for table t_user_symbol_address operations.
	UserSymbolAddress = userSymbolAddressDao{internal.NewUserSymbolAddressDao()}
)

// Add your custom methods and functionality below.
