// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GoCEX/internal/dao/internal"
)

// userBankDao is the data access object for the table t_user_bank.
// You can define custom methods on it to extend its functionality as needed.
type userBankDao struct {
	*internal.UserBankDao
}

var (
	// UserBank is a globally accessible object for table t_user_bank operations.
	UserBank = userBankDao{internal.NewUserBankDao()}
)

// Add your custom methods and functionality below.
